version: '3'
services:
  zookeeper:
    image: zookeeper:latest
    ports:
      - "2181:2181"
    networks:
      - uranus-storm-network
  nimbus:
    depends_on:
      - zookeeper
    image: xqhchen/test-uranus-storm
    command: >
      bash -c "/storm/compiled/apache-storm-2.2.0-SNAPSHOT/bin/storm nimbus"
    ports:
      - "49773:3773"
      - "49772:3772"
      - "49627:6627"
    networks:
      - uranus-storm-network
  supervisor:
    environment:
      JAVA_HOME: '/uranus/build/linux-x86_64-normal-server-release/images/j2sdk-image'
    depends_on:
      - zookeeper
      - nimbus
    image: xqhchen/test-uranus-storm
    devices:
      - /dev/isgx:/dev/isgx
      - /dev/mei0:/dev/mei0
    command: >
      bash -c "/opt/intel/sgxpsw/aesm/aesm_service && /storm/compiled/apache-storm-2.2.0-SNAPSHOT/bin/storm supervisor"
    expose:
      - "6700"
      - "6701"
      - "6702"
      - "6703"
    ports:
      - "6700"
      - "6701"
      - "6702"
      - "6703"
    networks:
      - uranus-storm-network
networks:
  uranus-storm-network:
